# Update Benchmarking plots
name: PlotUpdate

# The events that trigger the workflow
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    name: ${{ matrix.name }}

    strategy:
      fail-fast: false  # KS: Prevents cancellation of remaining jobs if one fails
      matrix:
        include:
          - name: PlotUpdate Beam
            cmake_options: -DUseCUDAProb3Linear=1 -DUseNuFASTLinear=1 -DUseProb3ppLinear=1 -DUseOscProb=1 -DUseNuSQUIDSLinear=1
            exec: DragRace
            argument: 1000 NuOscillatorConfigs/Binned_CUDAProb3Linear.yaml NuOscillatorConfigs/Binned_NuFASTLinear.yaml NuOscillatorConfigs/Binned_Prob3ppLinear.yaml NuOscillatorConfigs/Binned_OscProbLinear.yaml NuOscillatorConfigs/Binned_NuSQUIDSLinear.yaml
            title: TimingDistributionBeam.png
          - name: PlotUpdate ATM
            exec: DragRace
            cmake_options: -DUseCUDAProb3=1 -DUseOscProb=1
            argument: 50 NuOscillatorConfigs/Binned_CUDAProb3.yaml NuOscillatorConfigs/Binned_OscProb.yaml
            title: TimingDistributionATM.png
    container:
      image: ghcr.io/mach3-software/mach3:alma9latest

    steps:
    - uses: actions/checkout@v4

    - name: Get ImageMagick
      run:  dnf install ImageMagick -y

    - name: Get NuOscillator
      run: |
        cd /opt/
        git clone https://github.com/dbarrow257/NuOscillator.git NuOscillator
        cd NuOscillator
        git checkout ${{ github.head_ref }}
        mkdir build
        cd build
        cmake ../ -DUseGPU=0 -DUseMultithreading=1 -DUseDoubles=1 ${{ matrix.cmake_options }}

    - name: Build NuOscillator
      run: |
        cd /opt/NuOscillator/build
        make -j4 install # Build the project

    - name: Validations
      run: |
        source /opt/NuOscillator/build/Linux/bin/setup.NuOscillator.sh
        cd /opt/NuOscillator/
        build/Linux/bin//${{ matrix.exec }} ${{ matrix.argument }}

    - name: Checkout different branch
      run: |
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dbarrow257/NuOscillator.git Plot
        cd Plot
        git checkout gh-plots
        mv /opt/NuOscillator/TimingDistribution.pdf .

    - name: Convert PDF to PNG
      run: |
        cd Plot
        convert -density 150 'TimingDistribution.pdf[0]' -trim ${{ matrix.title }}

    - name: Configure Git and Push Update
      run: |
        cd Plot
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git add ${{ matrix.title }}
        git commit -m "Update ${{ matrix.title }}"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dbarrow257/NuOscillator.git gh-plots
